name: Build Veles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-webui:
    name: Build WebUI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "18.x"
      - run: yarn
        name: WebUI - Install Dependencies
        working-directory: webui
      - run: yarn build
        name: WebUI - Build
        working-directory: webui
      - name: WebUI - Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webui-dist
          path: webui/build

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: build-webui
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Download WebUI build
      uses: actions/download-artifact@v3
      with:
        name: webui-dist
        path: webui/build

    - name: Build with WebUI
      run: go build -o build/with-ui/ -tags withUI -v ./...

    - name: Build without WebUI
      run: go build -o build/without-ui/ -v ./...
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: veles-dist
        path: build

    - name: Test
      run: go test -v ./...
