name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: "18.x"

    - run: yarn
      name: WebUI - Install Dependencies
      working-directory: webui

    - run: yarn build
      name: WebUI - Build
      working-directory: webui

    - name: Build with WebUI
      run: go build -tags withUI -v ./...

    - name: Build without WebUI
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
