name: Create Release Artifacts

on:
  release:
    types: [published]

jobs:
  build-webui:
    name: Build WebUI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "18.x"
      - run: yarn
        name: WebUI - Install Dependencies
        working-directory: webui
      - run: yarn build
        name: WebUI - Build
        working-directory: webui
      - name: WebUI - Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webui-dist
          path: webui/build
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - name: Download WebUI build
        uses: actions/download-artifact@v3
        with:
          name: webui-dist
          path: webui/build
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.17.7.linux-amd64.tar.gz"
          extra_files: LICENSE README.md
          build_flags: '-tags withUI'
